#!/usr/bin/env python

DIR          = 'dir'
PANTHEON     = 'pantheon'
RATE         = '_rate'
RUNTIME      = '_runtime'
MAX_DELAY    = '_max-delay'
SEED         = '_seed'
BUFFER       = '_buffer'
FIRST_QUEUE  = '_first-queue'
SECOND_QUEUE = '_second-queue'
BASE         = '_base'
DELTA        = '_delta'
STEP         = '_step'
JITTER       = '_jitter'
LAYOUT_PATH  = 'layout-path'
